backend:
  name: git-gateway

media_folder: "site/images"
public_folder: "/images"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Opening hours, name: opening_hours, widget: text}
          # - {label: "Blurb", name: blurb, widget: object, fields: [
          #     {label: "Heading", name: "heading", widget: string},
          #     {label: "Text", name: "text", widget: "text"}]}
